apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
      - name: flight-service
        image: duynghia1009/flight-service:${IMAGE_TAG1}
        ports:
        - containerPort: 8082
