apiVersion: v1
kind: Service
metadata:
  name: flight-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30002
  selector:
    app: flight-service
